# Generated by Django 4.2.25 on 2025-10-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('localtion', models.CharField(max_length=30)),
                ('eir_code', models.CharField(max_length=7)),
                ('create_date', models.DateTimeField(verbose_name='create date')),
                ('create_by', models.DateTimeField(verbose_name='create by')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
