# Generated by Django 4.2.25 on 2025-10-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='create_by',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
