# Generated by Django 4.2.25 on 2025-10-22 15:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0002_alter_equipment_create_by_alter_equipment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingPile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pile_id', models.CharField(max_length=50, unique=True, verbose_name='Pile ID')),
                ('name', models.CharField(max_length=100, verbose_name='Pile Name')),
                ('pile_type', models.CharField(choices=[('fast', 'Fast Charging'), ('slow', 'Slow Charging')], max_length=20, verbose_name='Pile Type')),
                ('power', models.FloatField(verbose_name='Power Rating (kW)')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('pricing_id', models.CharField(max_length=50, verbose_name='Pricing Standard ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Awaiting Maintenance'), ('abandoned', 'Abandoned')], default='available', max_length=20, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='ChargingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True, verbose_name='Order ID')),
                ('customer_id', models.CharField(max_length=50, verbose_name='Customer ID')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Payment Method')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('charging_amount', models.FloatField(verbose_name='Charging Amount (kWh)')),
                ('transaction_status', models.CharField(choices=[('completed', 'Completed'), ('refunding', 'Refunding'), ('refunded', 'Refunded')], default='completed', max_length=20, verbose_name='Transaction Status')),
                ('pile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_management.chargingpile', verbose_name='Charging Pile')),
            ],
        ),
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Station Name')),
                ('station_id', models.CharField(max_length=50, unique=True, verbose_name='Station ID')),
                ('attributes', models.CharField(choices=[('shared', 'Shared Station'), ('personal', 'Personal Station')], max_length=20, verbose_name='Station Attribute')),
                ('station_type', models.CharField(choices=[('tesla', 'Tesla Exclusive'), ('mixed', 'Mixed Use')], max_length=20, verbose_name='Station Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('address', models.TextField(verbose_name='Detailed Address')),
                ('eircode', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[A-Z]\\d{2}[A-Z]{2}\\d{2}$', 'Invalid Eircode format (e.g. D01ZZ13)')], verbose_name='Eircode')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Application Pending'), ('creating', 'Under Construction'), ('deprecated', 'Deprecated')], default='pending', max_length=20, verbose_name='Status')),
                ('thumbnail', models.CharField(max_length=50, verbose_name='thumbnail ID')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(verbose_name='Balance')),
            ],
        ),
        migrations.CreateModel(
            name='PricingStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_id', models.CharField(max_length=50, unique=True, verbose_name='Pricing ID')),
                ('pricing_type', models.CharField(choices=[('unified', 'Unified Pricing'), ('custom', 'Custom Pricing')], max_length=20, verbose_name='Pricing Type')),
                ('time_period', models.CharField(max_length=100, verbose_name='Time Period')),
                ('electricity_fee', models.FloatField(verbose_name='Electricity Fee')),
                ('service_fee', models.FloatField(verbose_name='Service Fee')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
            ],
        ),
        migrations.CreateModel(
            name='RechargeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True, verbose_name='Order ID')),
                ('customer_id', models.CharField(max_length=50, verbose_name='Customer ID')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Payment Method')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('refunding', 'Refunding'), ('refunded', 'Refunded')], default='completed', max_length=20, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True, verbose_name='User ID')),
                ('name', models.CharField(max_length=100, verbose_name='User Name')),
                ('contact', models.CharField(max_length=50, verbose_name='User Contact')),
                ('password', models.CharField(max_length=100, verbose_name='User Password')),
                ('is_member', models.BooleanField(default=False, verbose_name='Is Member')),
            ],
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='equipment_management.user', verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='chargingpile',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_management.chargingstation', verbose_name='Belonging Station'),
        ),
    ]
